spring.application.name=library_backend_springboot_kt

# Connects to the database
spring.datasource.url = jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username = myuser
spring.datasource.password = mypassword

# Tells the app to create the necessary tables in the database
spring.jpa.hibernate.ddl-auto=create-drop